alphageek/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('redischat/', include('redischat.urls')),
    path('admin/', admin.site.urls),
]

redischat/urls.py
from django.urls import path, include
from . import views

app_name = 'redischat'
urlpatterns = [
	path('', views.page_index, name='index'),
	path('rooms', views.page_room_list, name='room_list'),
	path('new', views.page_room_new, name='room_new'),
	path('create', views.compute_room_create, name='room_create'),
	path('tmp', views.page_tmp, name='tmp'),
	path('rooms/<int:room_id>/', views.page_room, name='room'),
]

redischat/models.py
from datetime import datetime
from django.db import models
from django.conf import settings as django_settings

DB_REDIS = django_settings.DB_REDIS


# TODO : ajouter lez fonction bdd au model
class Message(models.Model):
    username = models.CharField(max_length=64)
    room = models.CharField(max_length=64)
    content = models.TextField()
    send_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('send_date',)


class RedisDB:

    def __init__(self, name):
        self.tmp_var = "hello from DB class"

    def says_hello(self):
        print(self.tmp_var)


class RedisMessage:

    def __init__(self, sender, content, room):
        self.sender = sender
        self.content = content
        self.room = room
        self.send_date = datetime.now()

    def save(self):
        DB_REDIS.set(f"{self.room}_{self.sender}", self.content)

redischat/views.py
import random
import time
from pprint import pprint

from django.shortcuts import render, redirect
from django.http import HttpResponse
import redis
from django.conf import settings as django_settings
from django.urls import reverse

from .models import Message, RedisMessage
from django.contrib.auth import authenticate, login

DB_REDIS = django_settings.DB_REDIS

APP_REDIS_PREFIX = "redischat/"


def page_index(request):
    """
    Home page of Redischat app
        - display app descriptif
        - display home page requested count
    """
    return render(request, APP_REDIS_PREFIX + 'index.html', {
        'room_count': get_room_count(),
        'view_count': get_view_count(),
    })


def page_room_list(request):
    """
    TODO : a faire
    TODO : rejoindre ou connexion
    """
    return render(request, APP_REDIS_PREFIX + 'room_list.html', {
        'room_count': get_room_count(),
    })


def page_room_new(request):
    """
    Room creation page ask to user :
        - room name
        - user pseudo
        - pseudo password
        - room color
    """
    return render(request, APP_REDIS_PREFIX + 'room_create.html', {
        'room_count': get_room_count(),
    })


def compute_room_create(request):
    if request.method != 'POST':
        return redirect("redischat:room_list")

    room_name = request.POST.get('room_name')
    room_owner = request.POST.get('room_owner_pseudo')
    room_owner_password = request.POST.get('room_owner_password')
    room_color = request.POST.get('room_color')

    room_id = redis_create_room(room_name, room_owner, room_color)
    if room_id is None:
        # TODO : message flash ?
        return redirect('redischat:room_create')

    user_id = redis_add_user_to_room(room_id, room_owner, room_owner_password)
    if user_id is None:
        # TODO : message flash ?
        return redirect('redischat:room_create')

    return redirect('redischat:room', room_id)


def page_room(request, room_id):
    # Growing spinner
    # TODO :recupéré tout les message d'un chat : évalué le temps de récupération / nombre de requete
    # TODO: user_name passé au template

    # messages = Message.objects.filter(room=room_name)[0:25]
    # messages = [
    #     RedisMessage(room_owner, "message 1", room_name),
    #     RedisMessage(room_owner, "message 2", room_name),
    #     RedisMessage(room_owner, "message 3", room_name)
    # ]
    room_name = redis_get_room_name_by_id(room_id)
    room_owner = redis_get_room_owner_by_id(room_id)
    room_color = redis_get_room_color_by_id(room_id)
    username = request.session['username'] if 'username' in request.session else None

    messages = Message.objects.filter(room=room_name)

    pprint(room_name)
    pprint(room_owner)
    pprint(room_color)

    if request.method == "POST":
        if "isAuth" in request.session:
            if "disconnect" in request.POST:
                request.session.pop("isAuth")

                return redirect("redischat:room", room_id)

        if "connexion" in request.POST:
            username = request.POST.get("conn_username")
            password = request.POST.get("conn_password")
            if username is not None and password is not None:
                conn = redis_conn_user_on_room(room_id, username, password)
                request.session['isAuth'] = room_id if conn else conn
                request.session['username'] = username if username else None

                return redirect("redischat:room", room_id)

        if "register" in request.POST:
            username = request.POST.get("reg_username")
            password = request.POST.get("reg_password")
            if username is not None and password is not None:
                reg = redis_add_user_to_room(room_id, username, password)
                request.session['isAuth'] = room_id if reg else reg
                request.session['username'] = username if username else None

                return redirect("redischat:room", room_id)

    return render(request, APP_REDIS_PREFIX + 'room.html', {
        'room_count': get_room_count(),
        'room_id': room_id,
        'room_name': room_name if room_name else None,
        'room_owner': room_owner if room_owner else None,
        'room_color': room_color if room_color else None,
        'username': username if username else None,
        'messages': messages,
    })


def page_tmp(request):
    # TODO : remove
    return render(request, APP_REDIS_PREFIX + 'tmp.html', {
        'room_count': get_room_count(),
    })


def page_redis(request):
    # TODO : remove
    return HttpResponse(f"Current hits : {get_view_count()}")


# ############
# # Function #
##############


def get_room_count():
    """
    Get number of room created
    """
    try:
        result = DB_REDIS.hlen("rooms")
        return result if result else None
    except redis.exceptions.ConnectionError as e:
        raise e


def get_view_count():
    retries = 5
    while True:
        try:
            return DB_REDIS.incr('view_count')

        except redis.exceptions.ConnectionError as exc:
            if retries == 0:
                raise exc

            retries -= 1
            time.sleep(0.5)


def redis_get_room_id_by_name(room_name):
    """
    Get room id from rooms tuples corresponding to room_name
    Return room_name id id exist Else None
    """
    try:
        result = DB_REDIS.hget("rooms", room_name)
        return result.decode("utf-8") if result else None
    except redis.exceptions.ConnectionError as e:
        raise e


def redis_get_room_name_by_id(room_id):
    """
    Get room name from rooms tuples corresponding to room_id
    Return room_id if exist Else None
    """
    try:
        result = DB_REDIS.hget(f"room:{room_id}", "name")
        return result.decode("utf-8") if result else None
    except redis.exceptions.ConnectionError as e:
        raise e


def redis_get_room_owner_by_id(room_id):
    """
    Get room owner from rooms tuples corresponding to room_id
    """
    try:
        result = DB_REDIS.hget(f"room:{room_id}", "owner")
        return result.decode("utf-8") if result else None
    except redis.exceptions.ConnectionError as e:
        raise e


def redis_get_room_color_by_id(room_id):
    """
    Get room color from rooms tuples corresponding to room_id
    """
    try:
        result = DB_REDIS.hget(f"room:{room_id}", "color")
        return result.decode("utf-8") if result else None
    except redis.exceptions.ConnectionError as e:
        raise e


def redis_get_room_last_user_id(room_id):
    """
    Get last room user id from rooms tuples corresponding to room_id
    Return last user id if exist Else None
    """
    try:
        result = DB_REDIS.hget(f"room:{room_id}", "last_user_id")
        return result.decode("utf-8") if result else None
    except redis.exceptions.ConnectionError as e:
        raise e


def redis_username_exist_in_room(room_id, username):
    """
    Check if username is free for the room
    Return true if exist Else false
    """
    try:
        result = DB_REDIS.hget(f"room:{room_id}:users", username)
        return True if result else False
    except redis.exceptions.ConnectionError as e:
        raise e


def redis_create_room(room_name, room_owner, room_color):
    """
    TODO = faire une descrpition
    tools
    """
    room_id = redis_get_room_id_by_name(room_name)
    if room_id is not None:
        print("##\n## Error : \n## room name already used\n##")
        return None

    while True:
        room_id = random.randint(0, 99999)
        if DB_REDIS.hget(f"room:{room_id}", 'owner') is None:
            break

    DB_REDIS.hmset(f"room:{room_id}", {
        "name": room_name,
        "owner": room_owner,
        "color": room_color,
        "last_user_id": 1,
    })
    DB_REDIS.hset("rooms", room_name, room_id)

    return room_id


def redis_add_user_to_room(room_id, user_name, user_pwd):
    """
    TODO = faire le com
    """
    user_id = redis_get_room_last_user_id(room_id)
    if redis_username_exist_in_room(room_id, user_name):
        print("##\n## Error : \n## user name already used in room\n##")
        return None

    DB_REDIS.hmset(f"room:{room_id}:user:{user_id}", {
        "password": user_pwd,
    })
    DB_REDIS.hset(f"room:{room_id}:users", user_name, user_id)
    DB_REDIS.hincrby(f"room:{room_id}", "last_user_id", 1)

    return user_id


def redis_conn_user_on_room(room_id, user_name, user_pwd):
    """
    TODO = faire le com
    """
    try:
        user_id = DB_REDIS.hget(f"room:{room_id}:users", user_name)
        user_id = user_id.decode('utf-8')
        print(f"####\n## user_id : '{user_id}'\n####")
        result = DB_REDIS.hget(f"room:{room_id}:user:{user_id}", "password")
        result = result.decode('utf-8')
        print(f"####\n## result : '{result}'\n####")

        return True if user_pwd == result else False
    except redis.exceptions.ConnectionError as e:
        raise e

redischat/templates/redischat/layout/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>{% block page_title %}Redischat{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    </head>

    <body style="position: relative; min-height: 100vh; padding-bottom: 5rem;">
    {% include 'redischat/layout/navbar.html' %}

    <div class="container" style="min-height: 80vh">
        {% block content %}{% endblock %}
    </div>

    <footer style="position: absolute; bottom: 0; width: 100%;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="https://www.linkedin.com/in/eymericsertgoz/" target="_blank">Eymeric
                        SERTGOZ</a> pour <a href="https://www.ipi-ecoles.com/" target="_blank">IPI - DigiTalents</a></p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
            integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
            integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
            crossorigin="anonymous"></script>
    <script>
        const popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        const popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })
    </script>
    </body>
</html>

redischat/templates/redischat/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'redischat:index' %}">Redischat</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name == 'redischat:index' %}active{% endif %}" aria-current="page" href="{% url 'redischat:index' %}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link position-relative  {% if request.resolver_match.view_name == 'redischat:room_list' %}active{% endif %}" href="{% url 'redischat:room_list' %}">Liste des salons<span
                            class="badge bg-primary position-relative"
                            style="top: -10px; font-size: 0.6rem;">{{ room_count }}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name == 'redischat:room_new' %}active{% endif %}" href="{% url 'redischat:room_new' %}">Créer un salon</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled {% if request.resolver_match.view_name == 'redischat:tmp' %}active{% endif %}" href="{% url 'redischat:tmp' %}">For les boi</a>
                </li>
            </ul>
            <span class="navbar-text">
        <a href="{% url 'home' %}"><i class="bi bi-house-door"></i></a>
      </span>
        </div>
    </div>
</nav>